name: Build and Test Sources

on: 
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    name: "Build Sources"
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v3
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable      
      - name: Install xcpretty
        run: bundle install      
      - name: Build and Test
        run: |
          set -o pipefail && \
          xcodebuild -scheme SimpleRoulette \
          clean build test \
          -destination "name=iPhone 12" \
          | bundle exec xcpretty